# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/clion-2017.2.2/bin/cmake/bin/cmake

# The command to remove a file.
RM = /opt/clion-2017.2.2/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/matthew/Coding/maximal clique enumerator/maximal_clique_enumerator"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/matthew/Coding/maximal clique enumerator/maximal_clique_enumerator"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/clion-2017.2.2/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/opt/clion-2017.2.2/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/matthew/Coding/maximal clique enumerator/maximal_clique_enumerator/CMakeFiles" "/home/matthew/Coding/maximal clique enumerator/maximal_clique_enumerator/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/matthew/Coding/maximal clique enumerator/maximal_clique_enumerator/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named maximal_clique_enumerator

# Build rule for target.
maximal_clique_enumerator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 maximal_clique_enumerator
.PHONY : maximal_clique_enumerator

# fast build rule for target.
maximal_clique_enumerator/fast:
	$(MAKE) -f CMakeFiles/maximal_clique_enumerator.dir/build.make CMakeFiles/maximal_clique_enumerator.dir/build
.PHONY : maximal_clique_enumerator/fast

graph.o: graph.cc.o

.PHONY : graph.o

# target to build an object file
graph.cc.o:
	$(MAKE) -f CMakeFiles/maximal_clique_enumerator.dir/build.make CMakeFiles/maximal_clique_enumerator.dir/graph.cc.o
.PHONY : graph.cc.o

graph.i: graph.cc.i

.PHONY : graph.i

# target to preprocess a source file
graph.cc.i:
	$(MAKE) -f CMakeFiles/maximal_clique_enumerator.dir/build.make CMakeFiles/maximal_clique_enumerator.dir/graph.cc.i
.PHONY : graph.cc.i

graph.s: graph.cc.s

.PHONY : graph.s

# target to generate assembly for a file
graph.cc.s:
	$(MAKE) -f CMakeFiles/maximal_clique_enumerator.dir/build.make CMakeFiles/maximal_clique_enumerator.dir/graph.cc.s
.PHONY : graph.cc.s

load_balancer.o: load_balancer.cc.o

.PHONY : load_balancer.o

# target to build an object file
load_balancer.cc.o:
	$(MAKE) -f CMakeFiles/maximal_clique_enumerator.dir/build.make CMakeFiles/maximal_clique_enumerator.dir/load_balancer.cc.o
.PHONY : load_balancer.cc.o

load_balancer.i: load_balancer.cc.i

.PHONY : load_balancer.i

# target to preprocess a source file
load_balancer.cc.i:
	$(MAKE) -f CMakeFiles/maximal_clique_enumerator.dir/build.make CMakeFiles/maximal_clique_enumerator.dir/load_balancer.cc.i
.PHONY : load_balancer.cc.i

load_balancer.s: load_balancer.cc.s

.PHONY : load_balancer.s

# target to generate assembly for a file
load_balancer.cc.s:
	$(MAKE) -f CMakeFiles/maximal_clique_enumerator.dir/build.make CMakeFiles/maximal_clique_enumerator.dir/load_balancer.cc.s
.PHONY : load_balancer.cc.s

main.o: main.cc.o

.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) -f CMakeFiles/maximal_clique_enumerator.dir/build.make CMakeFiles/maximal_clique_enumerator.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i

.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) -f CMakeFiles/maximal_clique_enumerator.dir/build.make CMakeFiles/maximal_clique_enumerator.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s

.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) -f CMakeFiles/maximal_clique_enumerator.dir/build.make CMakeFiles/maximal_clique_enumerator.dir/main.cc.s
.PHONY : main.cc.s

maximal_clique_enumerator.o: maximal_clique_enumerator.cc.o

.PHONY : maximal_clique_enumerator.o

# target to build an object file
maximal_clique_enumerator.cc.o:
	$(MAKE) -f CMakeFiles/maximal_clique_enumerator.dir/build.make CMakeFiles/maximal_clique_enumerator.dir/maximal_clique_enumerator.cc.o
.PHONY : maximal_clique_enumerator.cc.o

maximal_clique_enumerator.i: maximal_clique_enumerator.cc.i

.PHONY : maximal_clique_enumerator.i

# target to preprocess a source file
maximal_clique_enumerator.cc.i:
	$(MAKE) -f CMakeFiles/maximal_clique_enumerator.dir/build.make CMakeFiles/maximal_clique_enumerator.dir/maximal_clique_enumerator.cc.i
.PHONY : maximal_clique_enumerator.cc.i

maximal_clique_enumerator.s: maximal_clique_enumerator.cc.s

.PHONY : maximal_clique_enumerator.s

# target to generate assembly for a file
maximal_clique_enumerator.cc.s:
	$(MAKE) -f CMakeFiles/maximal_clique_enumerator.dir/build.make CMakeFiles/maximal_clique_enumerator.dir/maximal_clique_enumerator.cc.s
.PHONY : maximal_clique_enumerator.cc.s

search_tree_node.o: search_tree_node.cc.o

.PHONY : search_tree_node.o

# target to build an object file
search_tree_node.cc.o:
	$(MAKE) -f CMakeFiles/maximal_clique_enumerator.dir/build.make CMakeFiles/maximal_clique_enumerator.dir/search_tree_node.cc.o
.PHONY : search_tree_node.cc.o

search_tree_node.i: search_tree_node.cc.i

.PHONY : search_tree_node.i

# target to preprocess a source file
search_tree_node.cc.i:
	$(MAKE) -f CMakeFiles/maximal_clique_enumerator.dir/build.make CMakeFiles/maximal_clique_enumerator.dir/search_tree_node.cc.i
.PHONY : search_tree_node.cc.i

search_tree_node.s: search_tree_node.cc.s

.PHONY : search_tree_node.s

# target to generate assembly for a file
search_tree_node.cc.s:
	$(MAKE) -f CMakeFiles/maximal_clique_enumerator.dir/build.make CMakeFiles/maximal_clique_enumerator.dir/search_tree_node.cc.s
.PHONY : search_tree_node.cc.s

thread_context.o: thread_context.cc.o

.PHONY : thread_context.o

# target to build an object file
thread_context.cc.o:
	$(MAKE) -f CMakeFiles/maximal_clique_enumerator.dir/build.make CMakeFiles/maximal_clique_enumerator.dir/thread_context.cc.o
.PHONY : thread_context.cc.o

thread_context.i: thread_context.cc.i

.PHONY : thread_context.i

# target to preprocess a source file
thread_context.cc.i:
	$(MAKE) -f CMakeFiles/maximal_clique_enumerator.dir/build.make CMakeFiles/maximal_clique_enumerator.dir/thread_context.cc.i
.PHONY : thread_context.cc.i

thread_context.s: thread_context.cc.s

.PHONY : thread_context.s

# target to generate assembly for a file
thread_context.cc.s:
	$(MAKE) -f CMakeFiles/maximal_clique_enumerator.dir/build.make CMakeFiles/maximal_clique_enumerator.dir/thread_context.cc.s
.PHONY : thread_context.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... maximal_clique_enumerator"
	@echo "... graph.o"
	@echo "... graph.i"
	@echo "... graph.s"
	@echo "... load_balancer.o"
	@echo "... load_balancer.i"
	@echo "... load_balancer.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... maximal_clique_enumerator.o"
	@echo "... maximal_clique_enumerator.i"
	@echo "... maximal_clique_enumerator.s"
	@echo "... search_tree_node.o"
	@echo "... search_tree_node.i"
	@echo "... search_tree_node.s"
	@echo "... thread_context.o"
	@echo "... thread_context.i"
	@echo "... thread_context.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

